name: virtual-makeup
dependencies:
  - python=3.10.13
  - pip
  - pip:
      - streamlit==1.32.2
      - streamlit-webrtc
      - mediapipe==0.10.11
      - opencv-python-headless==4.9.0.80
      - numpy
      - Pillow
      - av

